import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { execSync } from 'child_process';
import {
  regenerateRulesForAdapter,
  regenerateAllRules,
  renderRulesWithDynamic,
  shouldRegenForMemory,
  triggerRulesRegen,
} from '../rulesGen';
import { cursorAdapter, claudeCodeAdapter, codexAdapter, adaptersWithRules } from '../editors';
import { MemoryStore } from '../store';

/**
 * Phase C4: rulesGen.ts tests.
 *
 * Covers:
 *   - shouldRegenForMemory() inclusion rules (layer + priority)
 *   - renderRulesWithDynamic() composition (static body + dynamic section)
 *   - regenerateRulesForAdapter() atomic write + idempotency
 *   - regenerateAllRules() iteration + inert-adapter skip
 *   - triggerRulesRegen() no-throw on missing project
 *
 * Uses real fs + MemoryStore — fixtures are temp dirs cleaned up per-test.
 */

function makeProject(): string {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'aide-rulesgen-'));
  // Minimal git + aide setup so MemoryStore can attach.
  execSync('git init -q', { cwd: root });
  execSync('git config user.name test', { cwd: root });
  execSync('git config user.email t@t.com', { cwd: root });
  const aideDir = path.join(root, '.aide');
  fs.mkdirSync(path.join(aideDir, 'memories', 'preferences'), { recursive: true });
  fs.mkdirSync(path.join(aideDir, 'memories', 'guidelines'), { recursive: true });
  fs.mkdirSync(path.join(aideDir, 'memories', 'technical'), { recursive: true });
  fs.mkdirSync(path.join(aideDir, 'memories', 'area_context'), { recursive: true });
  fs.mkdirSync(path.join(aideDir, 'cache'), { recursive: true });
  return root;
}

function cleanup(root: string): void {
  try {
    fs.rmSync(root, { recursive: true, force: true });
  } catch { /* best-effort */ }
}

const VARS = { contributor: 'test-contributor', tools_list: '- aide_recall\n- aide_remember' };

describe('shouldRegenForMemory', () => {
  it('returns true for priority:always regardless of layer', () => {
    expect(shouldRegenForMemory({ layer: 'technical', priority: 'always' })).toBe(true);
    expect(shouldRegenForMemory({ layer: 'area_context', priority: 'always' })).toBe(true);
  });

  it('returns true for preferences layer', () => {
    expect(shouldRegenForMemory({ layer: 'preferences' })).toBe(true);
    expect(shouldRegenForMemory({ layer: 'preferences', priority: 'normal' })).toBe(true);
  });

  it('returns true for guidelines layer', () => {
    expect(shouldRegenForMemory({ layer: 'guidelines' })).toBe(true);
  });

  it('returns false for technical/area_context memories without priority:always', () => {
    expect(shouldRegenForMemory({ layer: 'technical' })).toBe(false);
    expect(shouldRegenForMemory({ layer: 'area_context' })).toBe(false);
    expect(shouldRegenForMemory({ layer: 'technical', priority: 'normal' })).toBe(false);
  });

  it('returns false for null/undefined memory', () => {
    expect(shouldRegenForMemory(null)).toBe(false);
    expect(shouldRegenForMemory(undefined)).toBe(false);
  });
});

describe('renderRulesWithDynamic', () => {
  let root: string;
  let store: MemoryStore;

  beforeEach(() => {
    root = makeProject();
    store = new MemoryStore({ projectRoot: root });
  });

  afterEach(() => {
    store.close();
    cleanup(root);
  });

  it('returns static body only when store is empty', () => {
    const rendered = renderRulesWithDynamic(cursorAdapter, root, store, VARS);
    expect(rendered).toContain('# aide-memory: Persistent context across sessions');
    expect(rendered).not.toContain('AUTOGENERATED section');
    expect(rendered).not.toContain('## Current memory context');
  });

  it('appends dynamic section when preferences exist', () => {
    store.add({
      layer: 'preferences',
      what: 'prefer named exports over default',
      source: 'conversation',
    });
    const rendered = renderRulesWithDynamic(cursorAdapter, root, store, VARS);
    expect(rendered).toContain('AUTOGENERATED section');
    expect(rendered).toContain('## Current memory context');
    expect(rendered).toContain('## Session Preferences');
    expect(rendered).toContain('prefer named exports over default');
  });

  it('appends guidelines in Guidelines section', () => {
    store.add({
      layer: 'guidelines',
      what: 'all responses use snake_case',
      source: 'conversation',
    });
    const rendered = renderRulesWithDynamic(cursorAdapter, root, store, VARS);
    expect(rendered).toContain('## Guidelines');
    expect(rendered).toContain('all responses use snake_case');
  });

  it('places priority:always in ## Always section FIRST', () => {
    store.add({
      layer: 'technical',
      what: 'critical invariant',
      priority: 'always',
      source: 'conversation',
    });
    const rendered = renderRulesWithDynamic(cursorAdapter, root, store, VARS);
    expect(rendered).toContain('## Always');
    expect(rendered).toContain('critical invariant');
    const alwaysIdx = rendered.indexOf('## Always');
    const currentCtxIdx = rendered.indexOf('## Current memory context');
    expect(alwaysIdx).toBeGreaterThan(currentCtxIdx);
  });

  it('includes Cursor YAML frontmatter + agent_message note for cursor adapter', () => {
    const rendered = renderRulesWithDynamic(cursorAdapter, root, store, VARS);
    expect(rendered.startsWith('---\n')).toBe(true);
    expect(rendered).toContain('alwaysApply: true');
    expect(rendered).toContain('agent_message');
  });

  it('claude-code adapter produces no frontmatter + no agent_message note', () => {
    const rendered = renderRulesWithDynamic(claudeCodeAdapter, root, store, VARS);
    expect(rendered.startsWith('---\n')).toBe(false);
    expect(rendered).not.toContain('agent_message');
  });
});

describe('regenerateRulesForAdapter', () => {
  let root: string;

  beforeEach(() => { root = makeProject(); });
  afterEach(() => cleanup(root));

  it('writes .cursor/rules/aide-memory.mdc atomically for cursor adapter', () => {
    const store = new MemoryStore({ projectRoot: root });
    store.add({ layer: 'guidelines', what: 'test guideline', source: 'conversation' });
    store.close();

    const result = regenerateRulesForAdapter(cursorAdapter, root, VARS);
    expect(result.written).toBe(true);
    expect(result.dest).toBe('.cursor/rules/aide-memory.mdc');

    const destPath = path.join(root, '.cursor/rules/aide-memory.mdc');
    expect(fs.existsSync(destPath)).toBe(true);
    const content = fs.readFileSync(destPath, 'utf8');
    expect(content).toContain('test guideline');
    expect(content).toContain('AUTOGENERATED section');

    // No .tmp file left behind after atomic rename.
    expect(fs.existsSync(`${destPath}.tmp`)).toBe(false);
  });

  it('returns written: false for inert adapter (codex has supportsRules: false)', () => {
    const result = regenerateRulesForAdapter(codexAdapter, root, VARS);
    expect(result.written).toBe(false);
    // No codex rule file should have been written.
    expect(fs.existsSync(path.join(root, '.codex/rules'))).toBe(false);
  });

  it('second regen is idempotent and doesnt break on unchanged content', () => {
    const store = new MemoryStore({ projectRoot: root });
    store.add({ layer: 'preferences', what: 'idempotency test', source: 'conversation' });
    store.close();

    const first = regenerateRulesForAdapter(cursorAdapter, root, VARS);
    const firstContent = fs.readFileSync(path.join(root, first.dest), 'utf8');
    const second = regenerateRulesForAdapter(cursorAdapter, root, VARS);
    const secondContent = fs.readFileSync(path.join(root, second.dest), 'utf8');

    expect(first.written).toBe(true);
    expect(second.written).toBe(true);
    expect(firstContent).toBe(secondContent);
  });
});

describe('regenerateAllRules', () => {
  let root: string;

  beforeEach(() => { root = makeProject(); });
  afterEach(() => cleanup(root));

  it('regenerates for claude-code + cursor, skips codex/copilot/windsurf', () => {
    const store = new MemoryStore({ projectRoot: root });
    store.add({ layer: 'preferences', what: 'shared regen test', source: 'conversation' });
    store.close();

    const results = regenerateAllRules(adaptersWithRules(), root, VARS);
    const ids = results.map((r) => r.adapterId);
    expect(ids).toEqual(['claude-code', 'cursor']);
    for (const r of results) {
      expect(r.written).toBe(true);
      const destPath = path.join(root, r.dest);
      expect(fs.existsSync(destPath)).toBe(true);
      expect(fs.readFileSync(destPath, 'utf8')).toContain('shared regen test');
    }
  });

  it('per-adapter failures dont cascade', () => {
    // Simulated failure: force cursor adapter to have an unwritable dest by
    // creating a read-only file at the target. Since chmod is
    // platform-variant we just verify the function returns a results array
    // even when things go wrong — the swallow logic is what we're testing.
    const store = new MemoryStore({ projectRoot: root });
    store.close();
    const results = regenerateAllRules(adaptersWithRules(), root, VARS);
    expect(Array.isArray(results)).toBe(true);
    // claude-code should have written successfully regardless.
    const cc = results.find((r) => r.adapterId === 'claude-code');
    expect(cc?.written).toBe(true);
  });
});

describe('triggerRulesRegen — no-throw on broken project', () => {
  it('returns empty array when projectRoot is invalid', () => {
    const results = triggerRulesRegen(adaptersWithRules(), '/definitely/not/a/real/path');
    // Should NOT throw; may return [] or array with written:false entries.
    expect(Array.isArray(results)).toBe(true);
  });
});
