/**
 * Dynamic rule-file regeneration for Cursor (and future editors that need
 * session-start context injected via a file rather than a hook event).
 *
 * Why this exists:
 *   Cursor's `sessionStart.additional_context` is broken — staff-confirmed
 *   with no ETA (forum #158452). The official staff-endorsed workaround is
 *   to bake session-start content into a rules file with
 *   `alwaysApply: true`, which Cursor re-reads on every agent turn. See
 *   docs/specs/CURSOR_ONBOARDING.md §4 for the full rationale + §4.4 for
 *   the graceful upgrade path when Cursor fixes the underlying bug.
 *
 * How it works:
 *   1. regenerateRulesForAdapter(adapter, projectRoot) reads the current
 *      memory store + config via buildSessionStartContent (same code path
 *      Claude Code's SessionStart hook uses — one source of truth).
 *   2. Composes: adapter.ruleFrontmatter + AUTOGEN header + static shared
 *      body + dynamic "## Current memory context" section with the
 *      SessionStart content.
 *   3. Writes atomically via `.tmp` file + `fs.rename()` (POSIX-atomic —
 *      no torn read even under concurrent writers from parallel
 *      aide_remember invocations).
 *   4. Emits a stderr warning if cumulative `alwaysApply: true` content
 *      across all `.cursor/rules/*.mdc` exceeds ~2000 tokens (community
 *      soft cap — causes response quality degradation if exceeded).
 *
 * When to call:
 *   - aide-memory init / --force / --update-rules: always regenerate
 *   - aide-memory config <key> <value>: when key is injection.* or
 *     memories.softening.threshold (affects session-start content)
 *   - aide_remember / aide_update / aide_forget: when the memory is
 *     priority:"always" OR in preferences/guidelines layer (those layers
 *     feed the session-start injection)
 *   - aide-memory sync import: after successful import
 *
 * Call sites wire these triggers up — see src/memory/init.ts (init path),
 * src/memory/server.ts (MCP tool wrappers), and the config CLI.
 */

import * as fs from 'fs';
import * as path from 'path';
import { MemoryStore } from './store';
import { buildSessionStartContent } from './sessionStartContent';
import { buildRules } from './editors/rules';
import { EditorAdapter } from './editors/types';
import { detectContributor, MCP_TOOLS_LIST } from './init';
import { findPackageRoot } from './internal/paths';

/**
 * Community soft cap on cumulative `alwaysApply: true` rule content — Cursor
 * agents degrade in response quality above this threshold. Rough heuristic:
 * ~4 chars per token.
 */
const TOKEN_BUDGET_WARN_CHARS = 8000; // ~2000 tokens

/**
 * Marker line written into rules files to delimit the autogenerated section.
 * On regen, content BEFORE this line is preserved (user-editable static body
 * + frontmatter); content FROM this line onward is replaced with fresh
 * autogenerated content (priority memories + version notice).
 *
 * If a user removes the marker from their file, regen will still preserve
 * their edits — it appends a fresh marker block at the end rather than
 * overwriting the whole file.
 */
export const AUTOGEN_MARKER = '<!-- ─── AUTOGENERATED section — regenerated by aide-memory ─── -->';

/**
 * Build the autogen-marker block plus dynamic content (priority memories +
 * version notice) for adapters that need a dynamic section. This is what
 * replaces the existing autogen region of the rules file on regen.
 *
 * Returns an empty string if the adapter doesn't need dynamic rules OR if
 * there's nothing to inject (no preferences/guidelines/priority memories AND
 * no version update notice). The caller decides whether to skip the write
 * entirely in that case.
 */
function buildAutogenSection(
  adapter: EditorAdapter,
  projectRoot: string,
  store: MemoryStore,
): string {
  if (!adapter.needsDynamicRules) return '';

  const { content: dynamicContent } = buildSessionStartContent(projectRoot, store);

  let versionNotice = '';
  try {
    const os = require('os');
    const devSrcCli = path.resolve(findPackageRoot(), 'src', 'cli');
    if (!fs.existsSync(devSrcCli)) {
      const pkgPath = path.join(findPackageRoot(), 'package.json');
      const currentVersion = JSON.parse(fs.readFileSync(pkgPath, 'utf8')).version;
      const cachePath = path.join(os.homedir(), '.aide', 'update-check.json');
      if (fs.existsSync(cachePath)) {
        const cache = JSON.parse(fs.readFileSync(cachePath, 'utf8'));
        if (cache.latestVersion && cache.latestVersion !== currentVersion) {
          const cv = currentVersion.replace(/^v/, '').split('.').map(Number);
          const lv = cache.latestVersion.replace(/^v/, '').split('.').map(Number);
          const isNewer =
            lv[0] > cv[0] ||
            (lv[0] === cv[0] && lv[1] > cv[1]) ||
            (lv[0] === cv[0] && lv[1] === cv[1] && lv[2] > cv[2]);
          if (isNewer) {
            versionNotice = `\n## Update available\naide-memory v${cache.latestVersion} is available (current: v${currentVersion}). Tell the user to run \`npm update -g aide-memory\` to upgrade.\n`;
          }
        }
      }
    }
  } catch {
    // Non-fatal
  }

  if (!dynamicContent && !versionNotice) return '';

  const autogenHeader = [
    AUTOGEN_MARKER,
    '<!-- Content below reflects current memories + config. Do not edit by hand; -->',
    '<!-- changes will be overwritten on the next memory / config write.       -->',
    '',
  ].join('\n');

  const parts = [autogenHeader];
  if (dynamicContent) {
    parts.push('## Current memory context\n');
    parts.push(dynamicContent);
  }
  if (versionNotice) {
    parts.push(versionNotice);
  }
  return parts.join('\n') + '\n';
}

/**
 * Result of a regen attempt. `written` true means the file was (re)written;
 * false means no-op (adapter doesn't support rules OR content unchanged).
 */
export interface RegenResult {
  adapterId: string;
  dest: string;
  written: boolean;
  budgetWarning?: string;
}

/**
 * Return the current adapter-rendered rule file content, INCLUDING the
 * dynamic session-start section appended after the static shared body.
 *
 * Extracted so tests can inspect the rendered content without touching disk.
 */
export function renderRulesWithDynamic(
  adapter: EditorAdapter,
  projectRoot: string,
  store: MemoryStore,
  vars: { contributor: string; tools_list: string },
): string {
  const staticContent = buildRules(adapter, vars);

  // Adapters without `needsDynamicRules` (e.g., Claude Code) get static-only
  // rules. Their priority:always memories + version notice surface via the
  // SessionStart hook's `additionalContext` instead — which works natively on
  // those editors. Cursor has the dynamic block because its sessionStart
  // additional_context is broken (forum #158452, staff-confirmed).
  if (!adapter.needsDynamicRules) {
    return staticContent;
  }

  const autogenSection = buildAutogenSection(adapter, projectRoot, store);
  if (!autogenSection) return staticContent;

  return staticContent + '\n' + autogenSection;
}

/**
 * Regenerate a single adapter's rule file on disk. Idempotent + atomic.
 * Returns a RegenResult for telemetry / logging.
 *
 * Skips silently (returns { written: false }) when:
 *   - adapter.supportsRules is false
 *   - adapter has no rules entries
 *
 * Atomic write: content goes to `<dest>.tmp`, then fs.rename() swaps it
 * into place. Rename is atomic on POSIX, zero-chance of torn read.
 */
export function regenerateRulesForAdapter(
  adapter: EditorAdapter,
  projectRoot: string,
  vars: { contributor: string; tools_list: string },
): RegenResult {
  const result: RegenResult = {
    adapterId: adapter.id,
    dest: '',
    written: false,
  };

  if (!adapter.supportsRules || adapter.rules.length === 0) {
    return result;
  }

  // Single rule entry per adapter today (the interface supports multiple for
  // future editors that install more than one rule file).
  const rule = adapter.rules[0];
  result.dest = rule.dest;

  // Adapters without dynamic rules (Claude Code) have nothing to regen on
  // memory writes / config changes. Their content is static and only changes
  // when the user explicitly runs `aide-memory init` (with --force or
  // --update-rules). Skipping the write here preserves any user edits to
  // .claude/rules/aide-memory.md across memory operations.
  if (!adapter.needsDynamicRules) {
    return result;
  }

  const destPath = path.join(projectRoot, rule.dest);
  const destDir = path.dirname(destPath);
  if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });

  // Build only the autogen section. We'll splice it into the existing file
  // without touching content above the AUTOGEN_MARKER (which the user may
  // have edited).
  const store = new MemoryStore({ projectRoot });
  let autogenSection: string;
  try {
    autogenSection = buildAutogenSection(adapter, projectRoot, store);
  } finally {
    store.close();
  }

  // Compose the final rendered content. The intent: preserve user edits to
  // everything BEFORE the marker; only replace from the marker onward.
  //   - File doesn't exist → first regen, write full static + autogen
  //   - File exists, marker present → splice: keep before-marker, replace
  //     marker-onward with fresh autogen
  //   - File exists, marker absent → user removed it; preserve everything,
  //     append fresh autogen at the bottom (don't trample anything)
  let rendered: string;
  if (!fs.existsSync(destPath)) {
    const staticContent = buildRules(adapter, vars);
    rendered = autogenSection
      ? staticContent + '\n' + autogenSection
      : staticContent;
  } else {
    const existing = fs.readFileSync(destPath, 'utf8');
    const markerIdx = existing.indexOf(AUTOGEN_MARKER);
    if (!autogenSection) {
      // Nothing to inject this round. Leave file alone — user content stays.
      return result;
    }
    if (markerIdx === -1) {
      // No marker in user's file. Don't trample what they wrote; append.
      const trimmed = existing.replace(/\n+$/, '');
      rendered = trimmed + '\n\n' + autogenSection;
    } else {
      // Splice: preserve everything before the marker line, replace from
      // marker onward with fresh autogen content.
      const lineStart = existing.lastIndexOf('\n', markerIdx) + 1;
      const beforeMarker = existing.slice(0, lineStart).replace(/\n+$/, '');
      rendered = beforeMarker + '\n\n' + autogenSection;
    }
  }

  // Atomic write: temp file + rename. POSIX guarantees rename() is atomic
  // so readers (Cursor picking up the rules every turn) never see partial
  // content.
  const tmpPath = `${destPath}.tmp`;
  try {
    fs.writeFileSync(tmpPath, rendered, 'utf8');
    fs.renameSync(tmpPath, destPath);
    result.written = true;
  } catch (err) {
    // Best-effort cleanup on failure. Swallow — regeneration is a
    // convenience; a failure shouldn't block the caller (aide_remember
    // still succeeded, the rules file just stays stale until next trigger).
    try { if (fs.existsSync(tmpPath)) fs.unlinkSync(tmpPath); } catch { /* ignore */ }
    // Leave `written: false` in the result.
    // eslint-disable-next-line no-console
    console.warn(`aide-memory: failed to regenerate ${rule.dest}: ${(err as Error).message}`);
    return result;
  }

  // Token-budget check — cumulative alwaysApply:true content across all
  // .cursor/rules/*.mdc shouldn't exceed ~2000 tokens (Cursor community
  // best-practice, not platform-enforced). We only measure our own file
  // for now — a fuller check would scan sibling rule files.
  if (rendered.length > TOKEN_BUDGET_WARN_CHARS) {
    const approxTokens = Math.round(rendered.length / 4);
    result.budgetWarning =
      `${rule.dest} is ~${approxTokens} tokens — above Cursor's ~2000-token soft cap ` +
      `for alwaysApply rules. Consider lowering injection.maxChars or disabling layers ` +
      `you don't need in SessionStart (see docs/user/editors/cursor.md).`;
    // eslint-disable-next-line no-console
    console.warn(`aide-memory: ${result.budgetWarning}`);
  }

  return result;
}

/**
 * Convenience: regenerate rules for every adapter with supportsRules=true.
 * Used by init + sync import paths where we want to refresh all editors'
 * rule files in one call. Per-adapter errors don't cascade — each adapter's
 * regen is its own try/catch.
 */
export function regenerateAllRules(
  adapters: readonly EditorAdapter[],
  projectRoot: string,
  vars: { contributor: string; tools_list: string },
): RegenResult[] {
  const results: RegenResult[] = [];
  for (const adapter of adapters) {
    if (!adapter.supportsRules) continue;
    try {
      results.push(regenerateRulesForAdapter(adapter, projectRoot, vars));
    } catch (err) {
      // eslint-disable-next-line no-console
      console.warn(`aide-memory: rulesGen failed for ${adapter.id}: ${(err as Error).message}`);
      results.push({ adapterId: adapter.id, dest: adapter.rules[0]?.dest ?? '', written: false });
    }
  }
  return results;
}

/**
 * True if a memory should trigger a rules-file regeneration when stored,
 * updated, or removed. Mirrors the inclusion criteria of the SessionStart
 * injection:
 *   - priority: "always" — always surfaces at session start regardless of layer
 *   - layer: preferences or guidelines — default layers included in injection
 *
 * technical + area_context memories DON'T trigger regen by default because
 * they surface via path-recall hooks, not SessionStart injection. Users who
 * flip `injection.technical=true` or `injection.area_context=true` will
 * benefit from regen only on priority:"always" memories in those layers —
 * a known trade-off (documented in CURSOR_ONBOARDING.md §4).
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function shouldRegenForMemory(memory: any): boolean {
  if (!memory) return false;
  if (memory.priority === 'always') return true;
  if (memory.layer === 'preferences' || memory.layer === 'guidelines') return true;
  return false;
}

/**
 * Convenience trigger for callers that know `projectRoot` + an adapter list
 * but don't want to resolve contributor + tools_list themselves. Imports
 * MCP_TOOLS_LIST + detectContributor from init.ts (no circular — init.ts
 * imports from rulesGen, not the other way).
 *
 * Used by server.ts MCP tool wrappers + config CLI paths.
 *
 * Fully swallows errors — returns [] on any failure. Rule regeneration is
 * convenience; a failure must never propagate back to the memory write it
 * was triggered from.
 */
export function triggerRulesRegen(
  adapters: readonly EditorAdapter[],
  projectRoot: string,
): RegenResult[] {
  try {
    const contributor = detectContributor(projectRoot) || 'unknown';
    return regenerateAllRules(adapters, projectRoot, {
      contributor,
      tools_list: MCP_TOOLS_LIST,
    });
  } catch (err) {
    // eslint-disable-next-line no-console
    console.warn(`aide-memory: triggerRulesRegen failed: ${(err as Error).message}`);
    return [];
  }
}
